### PR TITLE
Fixed "to to" issue."

### PR DESCRIPTION
**Pull request by justinhart**

### CODE REVIEW

**Comment by kyordhel** [comment]
Thank you! 

I'll run some tests tomorrow to check we don't have issues like 

Please take an apple and bring **them** to the kitchen

**Comment by justinhart** [comment]
Awesome!

**Comment by msdejong** [comment]
one more thing in EEGPSR, one of the options for vbfollow is:

((come | go) (behind | after)) 

I don't think these quite make sense. Example of a sentence -  come after the Morgan at the tv couch 

'Go after / behind' makes sense in a lot of European languages, but doesn't mean follow in English. Should probably just be removed?

**Comment by justinhart** [comment]
I think that some of this is just limitations of the method of generating
the utterances. That utterance may not be particularly good, though, as it
doesn't really make sense. Not sure how to proceed on modifying that,
though.

**Comment by msdejong** [comment]
Well the vbfollow I think is just wrong - I can see how it happened, in Dutch (and I imagine in related European languages) saying "Go after/behind" someone does mean to follow them, so I imagine whoever wrote it probably intended that use.  I think the ((come | go) (behind | after)) can just be removed from vbfollow to fix this issue.

**Comment by justinhart** [comment]
So, the change looks like this?

$vbfollow  = follow | accompany

**Comment by kyordhel** [comment]
> 'Go after / behind' makes sense in a lot of European languages, but doesn't mean follow in English. Should probably just be removed?

Here I say no. Before EEGPSR the TC (that includes @justinhart) will have a brief meeting and pre-generate a set of commands for all the teams. We do this to ensure we are asking more or less the same to everyone and make the competition fair. In the past we had teams scoring full with *go-say-say*, and teams not being able to score due to lack of time in a *fetch-deliver-follow*.

I think @justinhart will make sure that all selected commands are properly formed and both, semantically and pragmatically correct.

**Comment by justinhart** [comment]
That sounds reasonable.

Justin

**Comment by kyordhel** [comment]
Don't get me wrong, @Michiel29, the rules says explicitly we must not modify the grammars one month before the competition. Removing duplicated words is OK (we people tend to skip one one word automatically when we find duplicates), but removing verbs might piss teams who already trained their recognizers/parsers/whatever.

**Comment by kyordhel** [comment]
One final thing. The person to congratulate (or blame) for the grammars is
me. I'm supposedly proficient in Spanish and fluent in English. My Dutch is
enough to buy vla, my German to get a bratwurst, and also can chew a couple
of words in Chinese, Japanese, and French. Nonetheless, I don't think any
of the latter have the minor impact in my English.

The thing about the come/go after/behind was based on some examples I found
in WordNet and maybe the Oxford thresaurus if memory fails me not (they
might be archaisms though).

So the question is. Is it correct to say "come with me"? And if that's the
case, would it be also "come with her/him/Jane/John"?

I would find incorrect the second one but not the first one. However,
recently I heard someone saying "can I come to the party?", having come
where I would have placed go.

Your remark just brought this to my head.

**Comment by msdejong** [comment]
I understand - perhaps something for next year then! 

For this specific case, 'come with me', 'come with', 'come with you' are correct, but 'come with her/him/Jane/John' is not - that's supposed to be 'go with her/him/Jane/John'. 

So 'go with' would be appropriate for $vbfollow, but 'come with' would no be. Go behind doesn't mean to follow someone, but to move behind the location where they are currently. Go after almost works, but it more means to chase someone down, like a cop.  

(I have no idea why, I realize there's no logical reason for any of this. English often doesn't make a lot of sense as a language)

**Pull request closed without merging**
